[phases.setup]
commands = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip"
]

[phases.install]
commands = [
  "/opt/venv/bin/pip install -r requirements.txt",
  "/opt/venv/bin/pip install gunicorn"   # explicitly install gunicorn if not in requirements.txt
]

[phases.build]
commands = [
  "/opt/venv/bin/python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
  "/opt/venv/bin/gunicorn ecommerce.wsgi"
]

[environment]
PATH = "/opt/venv/bin:$PATH"
