# Generated by Django 5.2.1 on 2025-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='ecommerce\\shop\templates\\shop\\image'),
        ),
    ]
